-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 09, 2017 at 10:46 AM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `trial`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE IF NOT EXISTS `recipes` (
  `ID` int(100) NOT NULL,
  `NAME` varchar(1000) NOT NULL,
  `TYPE` varchar(10) NOT NULL,
  `DIFFICULTY` varchar(20) NOT NULL,
  `VEGETARIAN` varchar(3) NOT NULL,
  `CALORIES` bigint(255) NOT NULL,
  `DURATION` bigint(255) NOT NULL,
  `SERVING` int(100) NOT NULL,
  `INGREDIENT` text NOT NULL,
  `METHOD` text NOT NULL,
  `URL` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`ID`, `NAME`, `TYPE`, `DIFFICULTY`, `VEGETARIAN`, `CALORIES`, `DURATION`, `SERVING`, `INGREDIENT`, `METHOD`, `URL`) VALUES
(1, 'Refried Bean Quesadillas', 'Food', 'EASY', 'YES', 487, 30, 4, '1 tbsp sunflower oil@\r\n1 onion, finely chopped@\r\n2 garlic cloves, finely chopped@\r\n1 tsp cumin seeds@\r\n400g can pinto or kidney beans, rinsed and drained@\r\n2 tsp smoked paprika@\r\n8 flour tortillas@\r\n100g cheddar or Gruyere , coarsely grated@\r\nhandful coriander leaves@\r\n200g tub fresh tomato salsa, plus extra to serve@\r\nsoured cream, to serve', '1. Heat the oil in a large frying pan and cook the onion and garlic for 2 mins. Add the cumin and cook for 1 min more. Tip in the beans, paprika and a splash of water. Using a potato masher, break the beans down as they warm through to make a rough puree. Season generously.\n\n2. Spread the refried beans onto 4 of the tortillas and scatter over the cheese and coriander. Spoon over the salsa, then top with the remaining tortillas to make 4 sandwiches. Wipe the frying pan with kitchen paper and return to the heat or heat a griddle pan. Cook each sandwich for 1-2 mins on each side until the tortillas are crisp and golden and the cheese is melting. Serve warm, cut into wedges, with extra salsa and soured cream for dipping.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--365499_11.jpg?itok=5ok7D5Hi'),
(2, 'Smoky Bacon Pot Noodle', 'Food', 'EASY', 'NO', 356, 10, 1, '1 rasher smoked back bacon, trimmed and chopped@\r\n2 spring onion, white and green separated and finely sliced@\r\n50g frozen pea@\r\nquarter tsp paprika@\r\n2 tsp cornflour@\r\n200ml vegetable stock@\r\n150g block straight-to-wok wheat noodle, or equivalent of dried, cooked@\r\nsplash Worcestershire sauce', '1. In a small non-stick pan, fry the bacon for a few mins, add the white parts of the spring onions, peas and paprika, then cook for 1 min more. Mix the cornflour with a little of the stock to get a paste, then stir this into the pan with the rest of the stock, noodles and a good splash of Worcestershire sauce. Simmer for a couple of mins until thick and saucy, then scatter with the green parts of spring onion.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--338814_11.jpg?itok=Uex2Adm4'),
(3, 'Quick Tomato Soup With Cheesy Garlic Dippers', 'Food', 'EASY', 'YES', 414, 25, 2, '400g can cherry tomatoes@\r\n1 tbsp caster sugar@\r\n100ml vegetable stock@\r\ndash each Tabasco and Worcestershire sauce@\r\n2 tbsp mascarpone@\r\nfew torn basil leaves (optional)@\r\n\r\nFor the dippers@\r\n1 medium ciabatta roll, halved@\r\n1 garlic clove, halved@\r\n125g ball mozzarella cheese, shredded', '1. Put the tomatoes, sugar, stock and sauces into a medium pan with some salt and pepper. Bring to a simmer and cook for 5-10 mins. Stir in the mascarpone and blend to a smooth soup. Return to the pan and keep warm while you make the dippers.\r\n\r\n2. Heat the grill to high and toast the ciabatta until golden. Rub with the garlic, season, then top with the cheese and grill until melted and golden. Slice into fingers and serve with the soup, sprinkled with the basil, if using.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--558500_11.jpg?itok=H7uuUXjl'),
(4, 'Quick Bean & Chorizo Chilli', 'Food', 'EASY', 'NO', 463, 20, 2, '100g chorizo, sliced@\r\n350g tub fresh tomato and chilli sauce (we used Waitrose)@\r\n400g can kidney beans, rinsed and drained@\r\n400g can chickpea, rinsed and drained@\r\nrice and natural yogurt, or jacket potatoes and soured cream, to serve', '1. Dry-fry the chorizo for a few mins in a non-stick frying pan until crisp. Carefully pour off any fat from the pan, then tip in the sauce and beans with 100ml water. Bring to a simmer, cover, then lower the heat and bubble for 10 mins. Spoon over rice and serve with yogurt.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--513575_11.jpg?itok=qr-Kakur'),
(5, 'Spanish Sardines On Toast', 'Food', 'EASY', 'NO', 420, 10, 2, '1 tbsp olive oil@\r\n1 garlic clove, chopped@\r\n1 red chilli, deseeded and chopped@\r\n1 lemon, zest and juice@\r\n2 x 120g cans sardines in sunflower oil, drained@\r\n4 slices brown bread@\r\nhalf small bunch parsley, chopped', '1. Heat the olive oil in a frying pan, then sizzle the garlic clove and red chilli. Add the lemon zest.\r\n\r\n2. Add the sardines and heat through for a few mins until warm.\r\n\r\n3. Toast the brown bread. Stir the parsley into the sardines, add a squeeze of lemon juice, then divide between the toast and serve.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--776558_11.jpg?itok=Av7K3SXu'),
(6, 'Sweet Potato & Pea Curry', 'Food', 'EASY', 'YES', 513, 40, 4, '3 tbsp curry paste from a jar@\r\n1 onion, finely chopped@\r\n450g potatoes, cut into chunks@\r\n2 large sweet potatoes (about 900g) cut into chunks@\r\n600ml vegetable stock, from a cube is fine@\r\n400ml can coconut milk@\r\n175g frozen peas@\r\nsmall bunch coriander, roughly chopped', '1. Heat the curry paste in a large pan and stir in the onion. Cover and cook for 5 mins, stirring occasionally, until softened. Add the potatoes, stock and coconut milk to the pan and bring to the boil.\r\n\r\n2. Turn the heat down and simmer the curry for 20 mins until the potato has softened. Add the peas, bring back to the boil and simmer for 2 mins more. Season to taste and spoon the curry into bowls. Scatter over the coriander before you tuck in.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--2733_11.jpg?itok=S7VzfRYq'),
(7, 'Moroccan Spiced Mince With Couscous', 'Food', 'EASY', 'YES', 497, 40, 4, '2 tbsp sunflower oil@\r\n2 medium onion, roughly chopped@\r\n350g pack Quorn mince@\r\n1 tbsp ground cumin@\r\n1 tsp ground cinnamon@\r\n2 tsp ground turmeric@\r\n100g ready-to-eat dried apricots quartered\r\n600ml vegetable stock@\r\n\r\nFor the couscous@\r\n280g couscous@\r\ngrated zest of 2 lemons@\r\n4 tbsp chopped fresh mint@\r\n50g unsalted cashews, toasted under the grill', '1. Heat the oil in a large nonstick pan, add the onions and cook gently for 5 minutes until they soften. Stir in the Quorn and spices (unlike meat and poultry, Quorn doesn’t need to be browned), then add the apricots and stock. Bring to the boil, then turn the heat down and cook gently for 10-15 minutes.\r\n\r\n2. Meanwhile, make up the couscous following the packet instructions – it will take about 450ml boiling water to give it a nice fluffy texture. Fork through the lemon zest and mint. Season to taste.\r\n\r\n3. Spoon the couscous onto serving plates, pile the Quorn mixture on top and scatter with the cashews.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--52341_12.jpg?itok=4fpJtOsZ'),
(8, 'Prawn & Coconut Laksa', 'Food', 'EASY', 'NO', 823, 20, 1, '2 tsp oil@\r\n1 garlic clove, crushed@\r\n1 spring onion, finely chopped@\r\n2 tsp finely chopped fresh root ginger@\r\n1 green chilli, deseeded and finely chopped@\r\njuice from ½ lime@\r\n100g raw prawns, any size@\r\n165ml can coconut milk@\r\n100ml chicken or vegetable stock@\r\n100g dried egg noodles@\r\nchopped coriander, to serve', '1. Heat the oil in a large pan or wok. When hot, throw in the garlic, spring onion, ginger and green chilli. Cook on a medium heat for 3-4 mins, then squeeze in your lime juice.\r\n\r\n2. Stir in the prawns, then add in the coconut milk and stock. Simmer gently for 5 mins on a low heat until the prawns are pink.\r\n\r\n3. Meanwhile, cook your egg noodles in a pan of boiling water for 4 mins until soft. Drain, then tip into the laksa pan. Season to taste, then serve in a bowl, topped with coriander.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--50683_11.jpg?itok=qlp9abnp'),
(9, 'Scrambled Omelette Toast Topper', 'Food', 'EASY', 'YES', 571, 10, 1, '2 egg@\r\n1 tbsp crème fraîche@\r\n25g cheddar, grated@\r\nsmall bunch chive, snipped@\r\n1 spring onion, sliced@\r\n1 tsp oil@\r\n3-4 cherry tomatoes, halved@\r\n2 slices crusty bread, toasted', '1. Beat together eggs, crème fraîche, cheese and chives with a little seasoning. Heat oil in a pan, then soften spring onion for a few mins. Add tomatoes and warm through, then pour in egg mixture. Cook over a low heat, stirring, until eggs are just set. Pile over toast.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--560516_11.jpg?itok=31QrCLEe'),
(10, 'Quick Sausage Bolognese', 'Food', 'EASY', 'NO', 657, 20, 4, '6 good-quality sausage, skins removed@\r\n1 tsp fennel seed@\r\n250g pack mushroom, sliced@\r\n150ml red wine (optional)@\r\n660g jar tomato pasta sauce (we used Loyd Grossman’s tomato & chilli)@\r\n300g penne@\r\ngrated or shaved Parmesan, to serve', '1. Heat a large, wide frying pan, then crumble in the sausage meat and fennel seeds (there’s no need to add any oil). Fry for a few mins until golden and the fat is released, stirring well to break up the meat. Add the mushrooms and fry for a few mins until beginning to soften. Stir in the wine now, if using, bubble for 1 min, then add the tomato sauce and heat through until bubbling.\r\n\r\n2. Meanwhile, boil the penne. When ready, drain and tip into the sauce. Mix well until completely coated, then divide between four plates, finishing with a little Parmesan.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--519470_12.jpg?itok=NJ0OUt01'),
(11, 'Sara\'s Iced Coffee', 'Beverage', 'EASY', 'YES', 155, 50, 4, '4 cups fresh brewed coffee@ \r\n1/2 teaspoon vanilla extract (optional)@ 1/4 cup white sugar@ \r\n1/4 cup boiling water@ \r\n3 cups crushed ice@ \r\n1/2 cup cream', '1. Refrigerate coffee until cool, about 30 minutes. Chill four glasses, if desired. Stir vanilla extract and sugar in the boiling water until dissolved. Refrigerate until cool, about 30 minutes. Divide the ice and chilled coffee evenly between the four glasses. Stir in cream and sugar mixture, to taste.', 'http://images.media-allrecipes.com/userphotos/250x250/668725.jpg'),
(12, 'Coffee Shake', 'Beverage', 'EASY', 'YES', 173, 5, 1, '1 teaspoon instant coffee granules@ \r\n3/4 cup milk@ \r\n1 teaspoon vanilla extract@ \r\n2 teaspoons white sugar, or to taste@ \r\n6 ice cubes@ \r\n2 teaspoons chocolate syrup (optional)', '1. Combine the instant coffee, milk, vanilla extract, sugar, ice, and chocolate syrup in a blender; blend until smooth.', 'http://images.media-allrecipes.com/userphotos/250x250/631819.jpg'),
(13, 'Cafe Latte', 'Beverage', 'EASY', 'YES', 63, 15, 4, '2 cups milk@\r\n1 1/3 cups hot freshly brewed dark roast espresso coffee', '1. Heat milk in a saucepan set over medium-low heat. Whisk briskly with a wire whisk to create foam. Brew espresso and pour into 4 cups. Pour in milk, holding back the foam with a spoon. Spoon foam over the top.', 'http://images.media-allrecipes.com/userphotos/250x250/188666.jpg'),
(14, 'Smooth Sweet Tea', 'Beverage', 'EASY', 'YES', 73, 30, 8, '1 pinch baking soda@ \r\n2 cups boiling water@ \r\n6 tea bags@ \r\n3/4 cup white sugar@ \r\n6 cups cool water', '1. Sprinkle a pinch of baking soda into a 64-ounce, heat-proof, glass pitcher. Pour in boiling water, and add tea bags. Cover, and allow to steep for 15 minutes.\r\n\r\n2. Remove tea bags, and discard; stir in sugar until dissolved. Pour in cool water, then refrigerate until cold.', 'http://images.media-allrecipes.com/userphotos/250x250/216335.jpg'),
(15, 'Honey Lemon Tea', 'Beverage', 'EASY', 'YES', 63, 5, 1, '1 cup water@ \r\n2 teaspoons honey@ \r\n1 teaspoon fresh lemon juice@ \r\n1 teaspoon white sugar, or to taste', '1. Pour water into a mug. Add honey and heat in the microwave for 1 minute and 30 seconds. Stir in lemon juice, mixing until honey is dissolved, then stir in the sugar.', 'http://images.media-allrecipes.com/userphotos/560x315/3392585.jpg'),
(16, 'Mexican Chicken Burger', 'Food', 'EASY', 'NO', 709, 18, 1, '1 chicken breast@\r\n1 tsp chipotle paste@\r\n1 lime, juiced@\r\n1-2 slices cheese@\r\n1 brioche bun, split@\r\n½ avocado@\r\n2 cherry tomatoes, chopped@\r\n3-4 pickled jalapeño slices, chopped@\r\n½ small garlic clove, finely grated', '1.Put the chicken breast between two pieces of cling film and bash with a rolling pin or pan to about 1cm thick. Mix the chipotle paste with half the lime juice and spread over the chicken.\r\nHeat a griddle pan over a high heat. \r\n\r\n2. Once hot, cook the chicken for 3 mins each side until cooked through, adding the cheese for the final 2 mins of cooking. Add the bun, cut-side down, to the griddle pan to toast lightly. Season the chicken.\r\n\r\n3. Meanwhile, mash the avocado with the remaining lime juice. Stir in the cherry tomatoes, jalapeño and garlic, and season with a little salt. Spread over the base of the bun, then add the chicken followed by the top of the bun.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/10/mexican-chicken-burger.jpg?itok=_AGDavEw'),
(17, 'Smoking Chilli Chicken & Sweetcorn Pizza', 'Food', 'EASY', 'NO', 494, 35, 4, '100g barbecue sauce@\r\n1-2 tbsp chipotle paste, or more if you like it spicy@\r\n2 large ready-made pizza base@\r\n175g mozzarella, grated (ready-grated is fine)@\r\n200g can sweetcorn, drained@\r\n300g jar red pepper, drained and torn into slices@\r\n200g cooked sliced chicken@\r\nsmall pack coriander, leaves only@\r\n2 fat green chilli, sliced, seeds removed (optional)', '1. Heat oven to 220C/200C fan/gas 7. Mix the barbecue and chipotle sauce in a bowl. Place the pizza bases on 2 large baking trays and spread over the sauce. Scatter the mozzarella over the pizzas, then top with the sweetcorn, peppers and chicken.\r\n\r\n2. Bake for 20 mins, swapping the trays over halfway through cooking, until the cheese has melted and the pizza is piping hot. Scatter with the coriander and the green chillies, if you like it extra spicy.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/pizza_4.jpg?itok=DzWsgUPl'),
(18, 'Pisto Con Huevos', 'Food', 'EASY', 'YES', 280, 80, 4, '2 tbsp olive oil@\r\n2 onions, finely chopped@\r\n4 garlic cloves, finely chopped@\r\n5 mixed peppers, chopped into chunks@\r\n1 heaped tsp dried oregano@\r\na few thyme sprigs, leaves picked@\r\n4 bay leaves@\r\n2 courgettes, chopped into chunks@\r\n1 aubergine, chopped into chunks@\r\n4 large tomatoes, roughly chopped@\r\n4 large eggs@\r\n½ small pack parsley, leaves roughly chopped', '1. Heat the oil in a large flameproof casserole dish or a cast-iron skillet over a low heat. Add the onions and a sprinkle of salt, cover and cook gently for 15 mins, stirring occasionally. Add the garlic and cook for another 2 mins.\r\n\r\n2. Next, throw in the peppers and cook over a medium heat, covered, for about 5 mins, stirring every so often, until the peppers are just tender.\r\n\r\n3. Mix in the oregano, thyme, bay leaves, some black pepper and a little salt, if needed. Tip in the courgettes and aubergine, combine thoroughly, and cook over a medium heat, covered, for 10 mins. Stir in the tomatoes, cover and cook for 20 mins, stirring occasionally.\r\n\r\n4. Carefully crack the eggs over the pisto – try not to break the yolks. Cook in the sauce on a medium heat for 5-6 mins until the eggs are cooked through but still a little soft, then scatter with parsley before serving.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/07/pisto-con-huevos.jpg?itok=UMOoNcFG'),
(19, 'Tortilla With Rocket & Parmesan\n', 'Food', 'EASY', 'NO', 382, 30, 4, '500g potato, peeled@\r\n3 tbsp olive oil, plus extra for drizzling@\r\n1 large onion, chopped@\r\n5 egg, beaten@\r\n100g bag rocket@\r\nhandful grated Parmesan, or shavings', '1. Cut the potatoes into slices, about finger thickness. Heat the oil in a non-stick frying pan, then tip in the potatoes and onion. When they start to sizzle and colour a little, pour in 225ml/8fl oz water - this will splatter so be careful. Simmer potatoes for 10 mins until tender.\r\n\r\n2. Pour off any excess liquid from the potatoes, then tip the eggs into the pan, season and stir lightly to mix. Return the pan to a medium heat and cook the tortilla until set on one side, about 5 mins. Place a plate on the top of the pan, hold it tightly and deftly turn it upside down so the tortilla comes out onto the plate. Add a bit of extra oil to the pan if it needs it, before sliding the tortilla back in to cook the reverse side - it only needs 5 mins more.\r\n\r\n3. Slide the tortilla onto a plate and cut it into 4 wedges. Top with a little pile of rocket, sprinkle over the parmesan, then drizzle with oil and serve.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/user-collections/my-colelction-image/2015/12/recipe-image-legacy-id--244_13.jpg?itok=NFs-H2MU'),
(20, 'Jerk Prawn & Coconut Rice Bowls\r\n', 'Food', 'EASY', 'NO', 531, 8, 2, '150g pack raw peeled king prawns@\r\n1 ½ tbsp jerk seasoning@\r\n400g can kidney beans in chilli sauce@\r\n250g pouch coconut rice', '1. Heat 1 tbsp flavourless oil in a large frying pan. Add the prawns and the jerk seasoning, and cook for 1-2 mins. Drain the beans, reserving 3 tbsp of the chilli sauce.\r\n\r\n2. Add the beans to the pan along with the reserved sauce and the coconut rice. Fry for 3-4 mins, then season with salt to taste and spoon into two bowls to serve.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/10/jerk-rice-bowl.jpg?itok=M_5Wheju'),
(21, 'Linguine With Garlic Butter Prawns\r\n', 'Food', 'EASY', 'NO', 547, 20, 2, '200g linguine@\r\n2-3 fat garlic clove, finely chopped@\r\n50g butter@\r\n175g pack raw shelled king prawn, de-veined and split in half lengthways@\r\nfinely grated zest 1 lemon, then cut the lemon into wedges@\r\nsmall pack parsley, chopped', '1. Boil the pasta following pack instructions. Meanwhile, very gently cook the garlic in the butter in a medium pan until softened. Add the prawns and cook until they just turn from grey to pink. It is important not to overcook them or they will be tough. Remove from the heat and stir in the zest and seasoning.\n\n2. Drain the pasta and toss into the pan with the prawn mixture and parsley until well mixed. Divide between two bowls and serve with the lemon wedges.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/linguine-with-garlic-butter-prawns.jpg?itok=XCDUnMls'),
(22, 'Garlic Bread Toasts\r\n', 'Food', 'EASY', 'NO', 230, 17, 12, '2 ciabatta loaves@\r\n140g butter, softened@\r\n4-6 garlic cloves, crushed@\r\nhandful parsley, chopped@\r\n2 tbsp finely grated Parmesan (or vegetarian alternative)', '1. Slice the bread in half lengthwise. Toast the crust side for 2 mins until really crispy. Mix together butter, garlic and parsley in a bowl. Spread over the cut bread halves. Sprinkle over the Parmesan. Just before serving place on a baking sheet, then cook under a hot grill for 5 mins until toasty and lightly golden. Let it cool for 1 min before cutting into thick slices.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--328149_12.jpg?itok=tLcHy0V9'),
(23, 'Chicken Katsu\r\n', 'Food', 'EASY', 'NO', 319, 40, 4, '4 skinless chicken breast@\r\n1 large egg, beaten@\r\n8 tbsp finely crushed cornflakes or panko crumbs@\r\n2 garlic clove, crushed@\r\n1-2 tbsp Korma paste@\r\n1 tbsp soy sauce@\r\n4 tbsp ketchup@\r\n2 tbsp honey@\r\n2 tbsp cornflour', '1. Heat oven to 200C/180C fan/gas 6. Dip the chicken in the egg, then coat in the cornflakes or crumbs. Space the chicken out on a non-stick baking tray and cook for 15-20 mins or until cooked through.\r\n\r\n2. Put the remaining ingredients in a pan. Pour in 500ml water and heat, stirring, until boiling and thickened. Cover and leave to simmer for 5 mins.\r\n\r\n3. Spoon some sauce onto 4 plates, slice the chicken breasts and place on top. Great served with some rice and soya beans with finely sliced red chilli.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--928562_10.jpg?itok=tQAGNgHH'),
(24, 'Sweet Potato Hash, Eggs & Smashed Avo\r\n', 'Food', 'EASY', 'YES', 558, 30, 2, '1 large ripe avocado@\r\n1 lime, juiced@\r\n1 tbsp olive oil@\r\n1 red onion, ends trimmed and spiralized on a flat blade@\r\n2 medium sweet potatoes, ends trimmed and spiralized into thin noodles@\r\n2 large eggs@\r\nsriracha, for drizzling', '1. Smash up the avocado with a fork, leaving some pieces chunky, then add the lime juice and season to taste.\r\n\r\n2. Heat the oil in a large, non-stick frying pan over a medium heat. Add the onion and cook for 2 mins, then stir in the sweet potato. Season and press the potato into the pan with the back of a wooden spoon. Cook for 10-15 mins, stirring occasionally, until the potato is softened and crisping at the edges.\r\n\r\n3. Make two spaces in the pan, crack in the eggs and cook for 2-3 mins until the whites are just set and the yolks runny. Dollop on the avocado and drizzle with sriracha to serve.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/12/sweet-potato-hash.jpg?itok=sGEExWuy'),
(25, 'Butternut Squash & Sage Risotto\r\n', 'Food', 'EASY', 'YES', 609, 50, 4, '1kg butternut squash, peeled and cut into bite-size chunks@\r\n3 tbsp olive oil@\r\nbunch sage, leaves picked, half roughly chopped, half left whole@\r\n1½ l vegetable stock@\r\n50g butter@\r\n1 onion, finely chopped@\r\n300g risotto rice (we used arborio)@\r\n1 small glass white wine@\r\n50g Parmesan or vegetarian alternative, finely grated', '1. Before you make the risotto, heat oven to 220C/fan 200C/gas 7. Toss the squash in 1 tbsp oil together with the chopped sage. Scatter into a shallow roasting tin and roast for 30 mins until it is brown and soft.\r\n\r\n2. While the squash is roasting, prepare the risotto. Bring the stock to the boil and keep on a low simmer. In a separate pan, melt half the butter over a medium heat. Stir in the onions and sweat gently for 8-10 mins until soft but not coloured, stirring occasionally. Stir the rice into the onions until completely coated in the butter, then stir continuously until the rice is shiny and the edges of the grain start to look transparent.\r\n\r\n3. Pour in the wine and simmer until totally evaporated. Add the stock, a ladleful at a time and stirring the rice over a low heat for 25-30 mins, until the rice is cooked al dente (with a slightly firm, starchy bite in the middle). The risotto should be creamy and slightly soupy. When you draw a wooden spoon through it, there should be a wake that holds for a few moments but not longer.\r\n\r\n4. At the same time, gently fry the whole sage leaves in a little olive oil until crisp, then set aside on kitchen paper. When the squash is cooked, mash half of it to a rough purée and leave half whole. When the risotto is just done, stir though the purée, then add the cheese and butter and leave to rest for a few mins. Serve the risotto scattered with the whole chunks of squash and the crisp sage leaves.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--1040452_11.jpg?itok=q_PHrXEm'),
(26, 'Supergreen Soup With Yogurt & Pine Nuts\r\n', 'Food', 'EASY', 'YES', 325, 30, 2, '2 tsp olive oil@\r\n1 onion, chopped@\r\n2 garlic cloves, crushed@\r\n1 potato (approx 250g), cut into small cubes@\r\n600ml vegetable stock@\r\n120g bag mixed watercress, rocket and spinach salad@\r\n150g pot natural yogurt@\r\n20g pine nuts, toasted@\r\nchilli oil, to serve (optional)', '1. Heat the oil in a medium saucepan over a low-medium heat. Add the onion and a pinch of salt, then cook slowly, stirring occasionally, for 10 mins until softened but not coloured. Add the garlic and cook for 1 min more.\r\n\r\n2. Tip in the potato followed by the veg stock. Simmer for 10-12 mins until the potato is soft enough that a cutlery knife will slide in easily. Add the bag of salad and let it wilt for 1 min, then blitz the soup in a blender until it’s completely smooth.\r\n\r\n3. Serve with a dollop of yogurt, some toasted pine nuts and a drizzle of chilli oil, if you like.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/04/supergreen-soup-with-yogurt-pine-nuts.jpg?itok=jUjRZHZI'),
(27, 'Cheesy Leek & Bacon Pasta\r\n', 'Food', 'EASY', 'NO', 556, 30, 4, '1 tbsp olive oil@\r\n300g leek, halved and finely sliced@\r\n8 rashers smoked streaky bacon, sliced@\r\n400g pasta shapes (we used penne)@\r\n100g herb & garlic soft cheese (we used Boursin)', '1. Heat the oil in a large non-stick frying pan. Add the leeks and 2 tbsp water, and cook for about 10 mins until very soft. Add the bacon, turn up the heat and fry until cooked.\r\n\r\n2. Meanwhile, cook the pasta following pack instructions. Drain and reserve a mug of the cooking water.\r\n\r\n3. Spoon cheese into the leek and bacon mix, adding some of the reserved cooking water. Season and stir gently over a low heat until melted. Toss through the cooked pasta, adding a little more cooking water, if needed, to help the sauce coat the pasta.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--1259456_8.jpg?itok=Ra60u-IR'),
(28, 'Creamy Ham, Leek & Mushroom Spaghetti\r\n', 'Food', 'EASY', 'NO', 384, 30, 4, '2 tsp olive oil@\r\n2 medium leeks, thinly sliced@\r\n200g chestnut mushroom, sliced@\r\n2 garlic clove, crushed@\r\n300g spaghetti@\r\n140g low-fat soft cheese (we used Philadelphia Light)@\r\n85g wafer-thin smoked ham, shredded@\r\nsmall pack basil@\r\n25g grated Parmesan', '1. Heat the oil in a large saucepan. Stir in the leeks, 2 tbsp water and some seasoning, cover, then cook for 5 mins over a medium heat until softened. Add the mushrooms and garlic, then cook for 3 mins more. Meanwhile, cook the spaghetti according to pack instructions, then drain, reserving a little of the cooking liquid.\r\n\r\n2. Stir the soft cheese into the leek and mushroom mixture, adding enough of the reserved pasta liquid to give a sauce-like consistency. Add the ham, basil leaves and Parmesan, then toss in the spaghetti.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--327851_12.jpg?itok=XhgioLYl'),
(29, 'Lime Marmalade Chicken', 'Food', 'EASY', 'NO', 466, 60, 4, '8 skin-on chicken thighs@\r\n2 tbsp olive oil@\r\n100g lime marmalade@\r\n2 garlic cloves, crushed@\r\n1 red chilli, finely chopped, deseeded if you don\'t like it too hot@\r\n1 tsp ground allspice@\r\n½ tsp dried oregano@\r\nsweet potato wedges, lime wedges, to serve (optional)', '1. Heat oven to 200C/180C fan/ gas 6. Put the thighs in a roasting tin and roast for 30 mins.\r\n\r\n2. Meanwhile, mix the oil, marmalade, garlic, chilli, allspice, oregano and some seasoning to make a marinade. Remove the thighs from the oven and brush all over with the marinade. Return to the oven and roast for another 20 mins until crispy and golden. Serve with some sweet potato wedges, lime wedges and salad, if you like. ', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2017/01/lime.jpg?itok=CF4LW4eW'),
(30, 'Cod & Chorizo Stew', 'Food', 'EASY', 'NO', 417, 27, 4, '1 tbsp olive oil\r\n1 large onion, finely chopped@\r\n200g cooking chorizo, chopped into small pieces@\r\n400g can chopped tomatoes@\r\n4 cod fillets@\r\n400g can butter beans, drained@\r\n½ small pack parsley, roughly chopped', '1. Heat the oil in a deep frying pan and add the onion. Cook over a medium heat for 5 mins until starting to soften. Add the chorizo and cook for another few mins to release the oil. Coat the onion in the chorizo oil, then tip in the tomatoes. Fill the can with water and tip that in too. Season and bring to the boil.\r\n\r\n2. Once boiling, season the cod fillets and nestle into the pan. Reduce the heat and gently simmer for about 7 mins. Gently mix in the butter beans and cook for 1-2 mins more until hot. Scatter with parsley and serve in bowls.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe/recipe-image/2016/03/cod-chorizo-stew.jpg?itok=DTIdd4fp'),
(31, 'Chickpea, Chorizo & Spinach Stew', 'Food', 'EASY', 'NO', 487, 30, 4, '3-4 tbsp extra-virgin olive oil@\r\n1 onion, chopped@\r\n1 carrot, finely diced@\r\n1 celery stick, finely diced@\r\nfew thyme sprigs@\r\n2 bay leaves@\r\n2 garlic clove, finely chopped@\r\n200g chorizo, diced@\r\n¼ tsp cinnamon@\r\n1 tsp hot smoked paprika@\r\n2 x 410g/14oz cans chickpeas, rinsed and drained@\r\n1-2 tbsp sherry vinegar@\r\n400g bag spinach leaves, washed and drained', '1. Heat the oil in a large pan, then gently fry the onion for 3-4 mins until it begins to soften. Stir in the carrot, celery, thyme and bay leaves. Season, then cook for 2-3 mins, stirring occasionally. Add the garlic, chorizo, cinnamon and smoked paprika. Gently fry until the vegetables soften and the chorizo starts to release its oils and crisp up.\r\n\r\n2. Stir in the chickpeas, vinegar and 150ml water, then bring to a simmer for 1-2 mins until the chickpeas have heated up. Add the spinach, then stir through the chickpeas until it wilts a little. Remove from the heat, season to taste, then serve warm with crusty bread.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--338530_11.jpg?itok=ehr29Cbu'),
(32, 'Roast Turkey With Citrus Butter\r\n', 'Food', 'MORE EFFORT', 'NO', 686, 265, 8, '1 turkey, about 6kg/13lb, giblets removed@\r\n140g butter, at room temperature@\r\nzest 1 lemon@\r\nzest 1 orange@\r\n2 thyme sprigs, leaves finely chopped@\r\n1 rosemary sprig, leaves finely chopped@\r\n4 large onion, halved@\r\n3 bay leaves@\r\n2 tbsp olive oil', '1. Heat oven to 180C/160C fan/gas 4. Pat the turkey dry all over with kitchen paper. Now weigh the bird and calculate the cooking time at 40 mins per kg. Mix the butter with the zests and herbs, and season well. Gently push your fingers under the turkey’s skin, starting from the neck end of the bird, easing the skin away from the flesh over both the breasts and the tops of the drumsticks. Spread the butter under the skin, pushing it in as far as you can, then smooth the skin back into place. Halve the lemon and orange and put in the turkey cavity along with 2 onion halves and the bay leaves.\r\n\r\n2. Rub turkey all over with oil and sprinkle with salt. Arrange remaining onions in the bottom of a large roasting tin to act as a trivet for the bird. Sit the turkey on top and completely cover both bird and tin with foil to make a tent. Roast according to your calculated cooking times.\r\n\r\n3. Thirty mins before the end of the cooking time, take out the turkey and turn up the oven to 200C/180C fan/gas 6. Remove the foil and return to the oven for a further 30 mins until golden. To test, pierce the fattest part of the thigh with a skewer – the juices that run out should be clear and not pink; keep cooking if the juices are pink and re-check at 10-min intervals. If you like your turkey meat almost falling off the bones, then wiggle the leg – it should give slightly if the meat is ready to come away from the bones, keep cooking and basting until it does.\r\n\r\n4. Rest the turkey, covered loosely with foil, for at least 30 mins and up to 1 hr before serving. Strain and reserve the cooking juices and keep the onions in the tin for making gravy (see \'Goes well with\', right).', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/user-collections/my-colelction-image/2015/12/recipe-image-legacy-id--464662_11.jpg?itok=K1-R9EU9'),
(33, 'Roast Turkey With Sage & Onion Butter And Marsala Gravy\r\n', 'Food', 'MORE EFFORT', 'NO', 812, 305, 8, '7kg/15lb 4oz fresh turkey@\r\n2 onions, halved@\r\n1 lemon, quartered@\r\n75g soft butter@\r\n3 tbsp finely chopped fresh sage@\r\n2 tbsp plain flour@\r\n200ml marsala wine or Madeira@\r\n400-500ml/14fl oz-18fl oz hot chicken stock@\r\n1 tbsp cranberry jelly', '1. Heat oven to 170C/150C fan/gas 3-4 and place the turkey in a large roasting tin. Tuck 3 of the onion halves and the lemon quarters into the cavity and season. Cover with foil, make sure there’s plenty of space between the turkey and foil for the air to circulate and seal the edges tightly so that no steam escapes. Roast for 4 hrs.\r\n\r\n2. Meanwhile, finely chop the remaining onion half, and mix with the butter and sage. Take the turkey out of the oven and raise the temp to 200C/180C fan/ gas 6. Brush the sage and onion butter all over the turkey and return to the oven, uncovered, for 45 mins until crisp and dark golden. If you’re making the roasties, then start them in the oven when the turkey goes back in, uncovered.\r\n\r\n3. Transfer the turkey to a warm serving plate, cover loosely with foil and leave to rest for 30 mins. Tip the juices out of the pan into a bowl, leave for a moment to settle, then scoop the buttery oil from the surface into a separate bowl. Spoon 2 tbsp of this oil back into the tin and return to the heat.\r\n\r\n4. Stir the flour into the tin using a wooden spoon, scraping the residue off the bottom of the tin as you go. Cook for 2 mins, then stir in the Marsala or Madeira and bring to the boil. Make the reserved turkey juices up to 500ml using hot chicken stock and pour into the tin. Bring to the boil and simmer for a few mins, then add cranberry jelly. Keep warm until ready to serve.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/user-collections/my-colelction-image/2015/12/recipe-image-legacy-id--487467_11.jpg?itok=hMwwhX8i'),
(34, 'Pepper, Pesto & Sweetcorn Calzones\r\n', 'Food', 'EASY', 'YES', 592, 55, 4, '500g pack bread mix@\r\n100g passata@\r\n290g jar roasted red peppers, drained and roughly chopped@\r\n100g frozen sweetcorn@\r\n125g ball mozzarella, torn into pieces@\r\n50g Parmesan (or vegetarian alternative), grated@\r\nhandful basil leaves, torn@\r\n50g pesto@\r\n1 egg, beaten@\r\ndressed salad leaves, to serve', '1. Make up the bread mix to pack instructions, reserving a little of the flour for dusting, and leave to prove for 30 mins.\r\n\r\n2. Line a baking tray with baking parchment. Tip the dough onto a floured surface and cut into quarters. Roll each ball of dough to a circle, roughly 20cm wide. Spread a little passata over each base, leaving a border of about 1cm around the edge. Season well.\r\n\r\n3. Top with the peppers, sweetcorn, mozzarella, Parmesan, basil and blobs of pesto. Fold each base in half, to make a half-moon shape, then squeeze the edges together, rolling them a little to stick and create a seal. Cover the tray with cling film and leave for 10 mins. Heat oven to 220C/200C fan/gas 7.\r\n\r\n4. Brush the calzones all over with beaten egg, then bake for 25-30 mins or until puffed and golden brown. Serve with dressed salad leaves.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/pepper-pesto-sweetcorn-calzones.jpg?itok=7XGt2LPe'),
(35, 'No-cook Chocolate Tart\r\n', 'Food', 'MORE EFFORT', 'YES', 487, 25, 8, '200g pack all-butter biscuit@\r\n100g butter@\r\n1 tbsp golden syrup or honey@\r\n100g bar dark chocolate@\r\n100g bar milk chocolate@\r\n1 tsp vanilla extract@\r\n2 tbsp icing sugar, plus extra for dusting@\r\n200ml whipping cream@\r\n3 tbsp crème fraîche, to decorate@\r\n200g raspberry, to serve', '1. Crush the biscuits by putting them in a large, strong, plastic food bag and bashing with a rolling pin. Melt the butter with the syrup or honey in the microwave, then stir in the biscuits. Press onto the base and up the sides of a 12 x 36cm rectangular tin (or 23-25cm round flan tin) and chill while you make the filling.\r\n\r\n2. Break up the two chocolate bars and put in a large bowl. Melt in the microwave for 2-3 mins on Medium, stirring halfway through. Stir in the vanilla extract, then sift in the icing sugar. Whip the cream until it just holds its shape, then fold into the melted chocolate. Pour into the prepared tin and smooth the top. Chill for at least 2 hrs or for up to 2 days.\r\n\r\n3. Just before serving, remove the tart from the tin and slide it onto a flat plate (loosen edges first with the tip of a small pointed knife). You will find it easier to remove the tart if you leave it at room temperature for 30 mins. Put a few tsps of crème fraîche along the centre of the tart (or around the edges if the tart is circular) and top each with a raspberry, then dust lightly with icing sugar. Cut into thin slices and serve with extra raspberries on the side.', 'http://www.bbcgoodfood.com/sites/default/files/styles/recipe/public/recipe_images/recipe-image-legacy-id--21900_11.jpg?itok=4ElzRQ5M'),
(36, 'Good Ol\' Alabama Sweet Tea', 'Beverage', 'EASY', 'YES', 97, 11, 16, '2 cups sugar@\r\n1/2 gallon water@\r\n1 tray ice cubes@\r\n3 family sized teabags of orange pekoe tea@ \r\n3 cups cold water, or as needed', '1. Pour the sugar into a large pitcher. Bring water to a boil in a large pan. When the water begins to boil, remove from the heat, and place the teabags in. Let steep for 5 to 6 minutes.\r\n\r\n2. Remove tea bags, and return tea to the heat. Bring just to a boil, then pour into the pitcher, and stir until the sugar is dissolved. Fill the pitcher half way with ice, and stir until most of it melts. Then fill the pitcher the rest of the way with cold water, and stir until blended.', 'http://images.media-allrecipes.com/userphotos/250x250/4284.jpg'),
(37, 'Mint Tea Punch', 'Beverage', 'EASY', 'YES', 94, 10, 10, '3 cups boiling water@ \r\n12 sprigs fresh mint@\r\n4 tea bags@ \r\n1 cup white sugar@ \r\n1 cup orange juice@ \r\n1/4 cup lemon juice@\r\n5 cups cold water@ \r\n3 orange slices for garnish (optional)@ \r\n3 lemon slices for garnish (optional)', '1. Place the tea bags and mint sprigs into a large pitcher. Pour boiling water over them, and allow to steep for about 8 minutes. Remove and discard the tea bags and mint leaves, squeezing out excess liquid. Stir in sugar until dissolved, then stir in the orange juice and lemon juice. Pour in the cold water. Serve over ice cubes, garnished with orange or lemon slices.', 'http://images.media-allrecipes.com/userphotos/560x315/432211.jpg'),
(38, 'Fuss Free Hot Cranberry Tea', 'Beverage', 'EASY', 'YES', 100, 15, 26, '1/2 gallon orange juice@ \r\n1 (64 fluid ounce) bottle cranberry-raspberry juice@ \r\n1 (16 ounce) can pineapple juice@ \r\n2 (2.25 ounce) packages small red cinnamon candies@ \r\n1/2 gallon water@ \r\n8 tea bags', '1. Combine the orange juice, cranberry-raspberry juice, pineapple juice, and cinnamon candies in a large stockpot; cook over high heat until the candies dissolve.\r\n\r\n2. Combine the water and tea bags in a separate pot and bring to a boil; reduce heat and simmer 5 to 10 minutes; pour into juice mixture. Serve hot.', 'http://images.media-allrecipes.com/userphotos/250x250/77890.jpg'),
(39, 'Coconut Oil Coffee', 'Beverage', 'EASY', 'YES', 224, 5, 2, '2 cups hot coffee@ \r\n2 tablespoons coconut oil@ \r\n2 tablespoons unsalted butter', '1. Blend coffee, coconut oil, and butter together in a blender until oil and butter are melted and coffee is frothy.\r\n', 'http://images.media-allrecipes.com/userphotos/560x315/1128816.jpg'),
(40, 'Eggnog Latte', 'Beverage', 'EASY', 'YES', 275, 5, 1, '1/3 cup 2% milk@ \r\n2/3 cup eggnog@ \r\n1 (1.5 fluid ounce) jigger brewed espresso@ \r\n1 pinch ground nutmeg', '1. Pour milk and eggnog into a steaming pitcher and heat to between 145 degrees F to 165 degrees F (65 to 70 degrees C) using the steaming wand. Brew the shot of espresso, then add to mug. Pour the steamed milk and eggnog into the mug, using a spoon to hold back the foam. Spoon foam over the top. Sprinkle nutmeg on top of the foam.', 'http://allrecipes.com/recipe/146962/eggnog-latte/photos/733733/'),
(41, 'Starbucks® Caramel Frappuccino Copycat Recipe', 'Beverage', 'EASY', 'YES', 271, 10, 2, '2 cups ice@ \r\n1 cup strong brewed coffee, cooled@ \r\n1 cup low-fat milk@ \r\n1/3 cup caramel sauce@ \r\n3 tablespoons white sugar', '1. Blend ice, coffee, milk, caramel sauce, and sugar together in a blender on high until smooth. Pour drink into two 16-ounce glasses.\r\n', 'http://images.media-allrecipes.com/userphotos/560x315/1104287.jpg'),
(42, 'Abbey\'s White Chocolate Latte', 'Beverage', 'EASY', 'YES', 270, 10, 2, '1 1/2 cups milk@ \r\n1 tablespoon heavy cream@ \r\n1/8 teaspoon vanilla extract@ \r\n1 tablespoon white sugar@ \r\n1/2 cup brewed espresso@ \r\n1/4 cup white chocolate chips, chopped', '1. Combine the milk and cream in a saucepan, and whisk over high heat until hot and frothy. Remove from heat and stir in the vanilla and sugar. Whisk together hot espresso and white chocolate chips in a mug until smooth. If you are making two, pour half into another mug. Top with the frothy hot milk and stir to blend in the flavoring.', 'http://images.media-allrecipes.com/userphotos/560x315/2107268.jpg'),
(43, 'Chocolate Mug Milkshake', 'Beverage', 'EASY', 'YES', 446, 15, 4, '4 cups chocolate ice cream@ \r\n2 cups milk@ \r\n1/4 cup brown sugar@ \r\n1/4 cup white sugar@ \r\n1/4 cup ground cinnamon', '1. In a blender, combine ice cream, milk, brown sugar, white sugar and cinnamon. Blend until smooth. Pour into glasses and serve.', 'http://images.media-allrecipes.com/userphotos/250x250/7649.jpg'),
(44, 'Fountain-Style Vanilla Malt Shake', 'Beverage', 'EASY', 'YES', 308, 8, 1, '1/2 cup cold milk@ \r\n1/4 cup carbonated water@ \r\n3 tablespoons malted milk powder@ \r\n1/2 teaspoon vanilla extract@ \r\n2 scoops vanilla ice cream', '1. In a blender, mix together milk, carbonated water, malted milk powder and vanilla extract. Scoop in ice cream. Blend until smooth. Pour into glass and serve.', 'http://images.media-allrecipes.com/userphotos/250x250/692229.jpg'),
(45, 'Chocolate-y Iced Mocha', 'Beverage', 'EASY', 'YES', 308, 10, 1, '1 1/4 cups cold coffee, divided@ \r\n1 envelope low-calorie hot cocoa mix@ \r\nice cubes, or as needed@ \r\n1/2 cup unsweetened almond milk@ \r\n2 tablespoons sugar-free chocolate syrup, or more to taste', '1. Heat 1/4 cup coffee in microwave in a mug until warmed, about 30 seconds. Stir cocoa mix into the coffee until dissolved.\r\n\r\n2. Fill a large glass with ice cubes. Pour 1 cup cold coffee and almond milk over the ice cubes; stir the cocoa mixture and chocolate syrup into the coffee and almond milk.', 'http://images.media-allrecipes.com/userphotos/560x315/1033896.jpg'),
(46, 'Avocado Blueberry Smoothie', 'Beverage', 'EASY', 'YES', 297, 5, 1, '1 cup frozen blueberries@ \r\n1 (6 ounce) container plain Greek-style yogurt@ \r\n1/2 cup almond milk@ \r\n1/2 cup water@ \r\n1/4 avocado - peeled, pitted, and diced', '1. Blend blueberries, yogurt, almond milk, water, and avocado in a blender until smooth.\r\n', 'http://images.media-allrecipes.com/userphotos/560x315/3549736.jpg'),
(47, 'Chocolate Banana Smoothie', 'Beverage', 'EASY', 'YES', 279, 5, 1, '1 banana@ \r\n1 tablespoon chocolate syrup@ \r\n1 cup milk@ \r\n1 cup crushed ice', '1. In a blender, combine banana, chocolate syrup, milk and crushed ice. Blend until smooth. Pour into glasses and serve.', 'http://images.media-allrecipes.com/userphotos/250x250/423574.jpg'),
(48, 'Easy Mango Banana Smoothie', 'Beverage', 'EASY', 'YES', 133, 10, 8, '2 mangos - peeled, seeded, and sliced@ \r\n2 bananas@ \r\n2 cups vanilla yogurt@ \r\n2 cups milk', '1. Blend mangos, banana, vanilla yogurt, and milk in a blender until smooth.', 'http://images.media-allrecipes.com/userphotos/560x315/1023445.jpg'),
(49, 'Summery Afternoon Smoothie', 'Beverage', 'EASY', 'YES', 334, 10, 1, '1 cup milk@ \r\n1/3 mango - peeled, seeded, and diced@ \r\n4 strawberries, hulled@ \r\n1/4 cup low-fat peach yogurt@ \r\n3 teaspoons honey', '1. Blend milk, mango, strawberries, yogurt, and honey together in a blender until smooth.', 'http://images.media-allrecipes.com/userphotos/560x315/1171399.jpg'),
(50, 'Banana and Strawberry Smoothie', 'Beverage', 'EASY', 'YES', 262, 5, 1, '1 banana@ \r\n5 strawberries, hulled@\r\n1 teaspoon ground cinnamon@ \r\n1 cup cold milk@ \r\n1 drop red food coloring (optional)', '1. Combine the banana, strawberries, cinnamon, milk, and food coloring in a blender; blend until smooth; serve immediately.', 'http://images.media-allrecipes.com/userphotos/560x315/421985.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `ID` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
